In [1]:
import numpy as np

In [4]:
ar = np.arange(64).reshape(8,8)
ar

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [11]:
ar = np.arange(64).reshape(4,2,4,2)
ar

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]]],


       [[[32, 33],
         [34, 35],
         [36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43],
         [44, 45],
         [46, 47]]],


       [[[48, 49],
         [50, 51],
         [52, 53],
         [54, 55]],

        [[56, 57],
         [58, 59],
         [60, 61],
         [62, 63]]]])

In [12]:
ar = np.arange(64).reshape(4,2,4,2).mean(-1)
ar

array([[[ 0.5,  2.5,  4.5,  6.5],
        [ 8.5, 10.5, 12.5, 14.5]],

       [[16.5, 18.5, 20.5, 22.5],
        [24.5, 26.5, 28.5, 30.5]],

       [[32.5, 34.5, 36.5, 38.5],
        [40.5, 42.5, 44.5, 46.5]],

       [[48.5, 50.5, 52.5, 54.5],
        [56.5, 58.5, 60.5, 62.5]]])

In [13]:
ar = np.arange(64).reshape(4,2,4,2).mean(-1).mean(1)
ar

array([[ 4.5,  6.5,  8.5, 10.5],
       [20.5, 22.5, 24.5, 26.5],
       [36.5, 38.5, 40.5, 42.5],
       [52.5, 54.5, 56.5, 58.5]])

In [15]:
ar = (np.arange(64).reshape(4, 2, 4, 2).mean(-1).mean(1) + 0.5).astype('u2')
ar

array([[ 5,  7,  9, 11],
       [21, 23, 25, 27],
       [37, 39, 41, 43],
       [53, 55, 57, 59]], dtype=uint16)

In [16]:
ar = np.arange(64).reshape(2,4,2,4)
ar

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]]],


       [[[32, 33, 34, 35],
         [36, 37, 38, 39]],

        [[40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55]],

        [[56, 57, 58, 59],
         [60, 61, 62, 63]]]])

In [17]:
ar = np.arange(64).reshape(2,4,2,4).mean(-1)
ar

array([[[ 1.5,  5.5],
        [ 9.5, 13.5],
        [17.5, 21.5],
        [25.5, 29.5]],

       [[33.5, 37.5],
        [41.5, 45.5],
        [49.5, 53.5],
        [57.5, 61.5]]])

In [18]:
ar = np.arange(64).reshape(2,4,2,4).mean(-1).mean(1)
ar

array([[13.5, 17.5],
       [45.5, 49.5]])